// Generated by Selenium IDE
using july_2021.Model;
using NUnit.Framework;
using OpenQA.Selenium;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;


[TestFixture]
public class BillingorderTest
{
    private IWebDriver driver;
    public BillingorderTest(IWebDriver driver)
    {
        this.driver = driver;
    }
        [Test]
        public void SubmitBillingOrder(BillingOrder order)
        {
            driver.Navigate().GoToUrl("http://qaauto.co.nz/billing-order-form/");
            driver.Manage().Window.Size = new System.Drawing.Size(696, 680);
            driver.FindElement(By.Id("wpforms-locked-24-field_form_locker_password")).Click();
            driver.FindElement(By.Id("wpforms-locked-24-field_form_locker_password")).SendKeys("Testing");
            driver.FindElement(By.Id("wpforms-submit-locked-24")).Click();
            driver.FindElement(By.Id("wpforms-24-field_0")).SendKeys(order.firstName);

            driver.FindElement(By.Id("wpforms-24-field_0-last")).SendKeys(order.lastName);

            driver.FindElement(By.Id("wpforms-24-field_1")).SendKeys(order.email);

            driver.FindElement(By.Id("wpforms-24-field_3")).SendKeys(order.addressLine1);
            driver.FindElement(By.Id("wpforms-24-field_2")).SendKeys("(095) 868-6790");
            driver.FindElement(By.Id("wpforms-24-field_3-city")).SendKeys("Naranpura");
            driver.FindElement(By.Id("wpforms-24-field_3-postal")).SendKeys("38006-3232323");

            driver.FindElement(By.Id("wpforms-24-field_3-address2")).SendKeys("12121");
            driver.FindElement(By.Id("wpforms-24-field_3-city")).Click();
            driver.FindElement(By.Id("wpforms-24-field_3-city")).SendKeys("32323");
            driver.FindElement(By.Id("wpforms-24-field_3-state")).Click();
        {
            var dropdown = driver.FindElement(By.Id("wpforms-24-field_3-state"));
            dropdown.FindElement(By.XPath("//option[. = 'Georgia']")).Click();
        }
            driver.FindElement(By.Id("wpforms-24-field_3-postal")).Click();
        
        driver.FindElement(By.Id("wpforms-24-field_3")).Click();
        driver.FindElement(By.Id("wpforms-24-field_3")).Click();
        driver.FindElement(By.Id("wpforms-24-field_3")).SendKeys("asasas");
        driver.FindElement(By.Id("wpforms-24-field_4_1")).Click();

        driver.FindElement(By.Id("wpforms-24-field_6")).SendKeys("assas");
        driver.FindElement(By.Id("wpforms-submit-24")).Click();


        // Assert.That(driver.FindElement(By.CssSelector("#wpforms-confirmation-24 > p")).Text, Is.EqualTo("Thanks for contacting us! We will be in touch with you shortly."));
        driver.FindElement(By.CssSelector(".wpforms-form-page-footer > p")).Click();
        }
    }


    
  

